name: Opendds_arm64
on:
  workflow_dispatch:
jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
      - uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build dockerImages
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: agasdrm/blog:latest,agasdrm/blog:${{ github.run_number }}
          platforms: linux/amd64,linux/arm64
