name: Opendds_arm64
on:
  workflow_dispatch:
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v5
        
        with:
          context: .
          tags: kittyhapp/opendds:latest,kittyhapp/opendds:${{ github.run_number}}
          platforms: linux/amd64,linux/arm64
